### PR TITLE
docs: updating readme to deprecate repo

### PR DESCRIPTION
**Pull request by esacteksab**
- Deprecating
- Use Trivy or Grype instead

### CODE REVIEW

**Comment by rpdelaney** [comment]
@esacteksab @jsclarridge Is this ready to merge?

**Comment by jsclarridge** [comment]
I can review this today and post another update later. I wanted to test https://github.com/trussworks/ecr-scan/tree/barry-migrate-modern-layout first. And if deprecating the repo, I have some ideas for additional text that could be added to the note to provide more context.

**Comment by jsclarridge** [comment]
@esacteksab @rpdelaney I pushed a change (https://github.com/trussworks/ecr-scan/pull/207/commits/929f83aef2fef15556390ebdcb6f0683654838bc), using some of the boilerplate language we've used for deprecating terraform modules (e.g., https://github.com/trussworks/terraform-aws-lambda-ecr-scan, which was associated with this repo). If you all are good with that change, then I think this is ready to merge.

**Comment by rpdelaney** [comment]
Ship it!

**Review by jsclarridge — APPROVED** [review]

**Pull request merged**
